### ISSUE TITLE
Document Model code generation

### ISSUE THREAD

**Issue by acaldas** [powerhouse-inc/codegen#5]
https://github.com/orgs/powerhouse-inc/projects/1/views/1?filterQuery=epic%3A%22Document+Model+code+generation%22

This is an epic issue. List of individual issues is below:

- [x] powerhouse-inc/codegen#4  
- [ ] https://github.com/powerhouse-inc/document-model/issues/7
- [x] https://github.com/powerhouse-inc/powerhouse/issues/7
- [x] https://github.com/powerhouse-inc/powerhouse/issues/2
